### ISSUE TITLE
Deregister

### ISSUE THREAD

**Issue by eigengravy** [eigengravy/tinyfl#5]
De-register party from aggregator and graceful shutdown.

- [ ] Implement De-register message dataclass.
- [ ] Send de-register request to aggregator when a party is shutting down. 
- [ ] Handle de-register message on the aggregator to remove party from client set.

**Comment by Ceres445** [comment]
I would like to be assigned this

**Comment by Ceres445** [comment]
@eigengravy should I add logging for client registration and degregistration on the aggregator side

**Comment by eigengravy** [comment]
Sure, that would be great.
